image:
  file: dockerfile  
workspaceLocation: "."
tasks:
  - init:  echo 'Welcome to Angular dev environment'
  - command: >
      ng new hello-world --interactive=false 
      cd hello-world 
      ng serve -o --port 4400      
ports:
  - port: 8000
    onOpen: open-preview    
  - port: 4200
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 4400
    onOpen: open-preview
